delta: Mesh Class Reference
Mesh Class Reference
Public Member Functions
Mesh (VecDoub &coords, VecDoub &val)
Constructor for Mesh class. Constructs the triangulation from input coordinates.
size_t size ()
Get number of coordinate pairs.
size_t numTriag ()
Get the number of total triangles.
std::vector< size_t > edgesOfTriag (size_t t)
Find the half edges coresponding to the input triangle.
std::vector< size_t > pointsOfTriag (size_t t)
Find the indices to the points of triangles in the coord list.
size_t triagOfEdge (size_t e)
Find the triangle that the given half edge is in.
std::vector< MeshPoint > coordsOfTriag (size_t t)
Give the coordinates of the vertices of triangle.
LineSeg edgeToLineSeg (size_t e)
Give the coordinates of the end points of an half edge (head, tail)
size_t neighborTriag (size_t e)
Find the opposite halfedge of the given edge, and then the triangle it belongs to.
VecDoub barycentric (MeshPoint point, size_t t)
Calculates the barycentric coordinate of point in triangle.
bool isInTriag (MeshPoint point, size_t t)
Whether a point is in the current triangle.
MeshPoint centroid (size_t t)
Finds the centroid of the trianglge.
std::vector< size_t > search (MeshPoint p, size_t init)
Look for which triangle the point is in by "walking" through the triangulation.
size_t walk (MeshPoint p, size_t t_now)
Walks to the next closest triangle.
double interp (MeshPoint p, size_t init)
Linear interpolation on triangular grid.
Detailed Description
Definition at line 86 of file Mesh.hpp.
Constructor & Destructor Documentation
Mesh()
Mesh::Mesh (VecDoub & coords, VecDoub & val)
Constructor for Mesh class. Constructs the triangulation from input coordinates.
Parameters
coords Set of coordinates for input points, as one vector {x1, y1, x2, y2, ...}
Definition at line 68 of file Mesh.cpp.
Member Function Documentation
barycentric()
VecDoub Mesh::barycentric (MeshPoint point, size_t t)
Calculates the barycentric coordinate of point in triangle.
Parameters
point coordinate {x, y} of query point
t index of triangle
Returns
Barycentric coordinate {lambda1, lambda2, lambda3}; expression from wikipedia
Definition at line 187 of file Mesh.cpp.
References coordsOfTriag().
Referenced by interp(), and isInTriag().
centroid()
MeshPoint Mesh::centroid (size_t t)
Finds the centroid of the trianglge.
Parameters
t Index of the triangle
Note
This is a point that is gauranteed to be inside the triangle. Its barycentric coordinate should always be {1/3, 1/3, 1/3}
Definition at line 221 of file Mesh.cpp.
References coordsOfTriag().
Referenced by walk().
coordsOfTriag()
std::vector< MeshPoint > Mesh::coordsOfTriag (size_t t)
Give the coordinates of the vertices of triangle.
Parameters
t index of triangle
Returns
coordinates of vertices
Definition at line 137 of file Mesh.cpp.
References pointsOfTriag().
Referenced by barycentric(), and centroid().
edgesOfTriag()
std::vector< size_t > Mesh::edgesOfTriag (size_t t)
Find the half edges coresponding to the input triangle.
Parameters
t index of triangle
Returns
Indices of the edges of the t-th triangle
Definition at line 93 of file Mesh.cpp.
Referenced by pointsOfTriag(), and walk().
edgeToLineSeg()
LineSeg Mesh::edgeToLineSeg (size_t e)
Give the coordinates of the end points of an half edge (head, tail)
Parameters
e index of halfedge
Returns
coordinates of endpoints
Definition at line 149 of file Mesh.cpp.
Referenced by walk().
interp()
double Mesh::interp (MeshPoint p, size_t init)
Linear interpolation on triangular grid.
Parameters
p Query point for interpolation
init Index of the initial angle to start searching in
Search for which triangle the point is in, then find the barycentric coordinate of the point. The interpolated value is then sum(lambda_i * val_i).
Definition at line 285 of file Mesh.cpp.
References barycentric(), pointsOfTriag(), and search().
isInTriag()
bool Mesh::isInTriag (MeshPoint point, size_t t)
Whether a point is in the current triangle.
Parameters
point coordinate {x, y} of the query point
t index of the current triangle
Calculates the barycentric coordinate. If all coordinates are between [0, 1], the point is in the triangle.
Definition at line 211 of file Mesh.cpp.
References barycentric().
Referenced by search().
neighborTriag()
size_t Mesh::neighborTriag (size_t e)
Find the opposite halfedge of the given edge, and then the triangle it belongs to.
Parameters
e index of the half edge in the current triangle.
Returns
index of the neighbor triangle; -1 if there's no neighbor
Definition at line 174 of file Mesh.cpp.
References triagOfEdge().
pointsOfTriag()
std::vector< size_t > Mesh::pointsOfTriag (size_t t)
Find the indices to the points of triangles in the coord list.
Parameters
t index of triangle
Returns
indices of points
Definition at line 109 of file Mesh.cpp.
References edgesOfTriag().
Referenced by coordsOfTriag(), and interp().
search()
std::vector< size_t > Mesh::search (MeshPoint p, size_t init)
Look for which triangle the point is in by "walking" through the triangulation.
Parameters
p The point to search for
init Index of the triangle to start with
Definition at line 235 of file Mesh.cpp.
References isInTriag(), and walk().
Referenced by interp().
triagOfEdge()
size_t Mesh::triagOfEdge (size_t e)
Find the triangle that the given half edge is in.
Parameters
e index of the half edge
Returns
Index of the resulting triangle (index t that the triangle starts in)
Definition at line 123 of file Mesh.cpp.
Referenced by neighborTriag(), and walk().
walk()
size_t Mesh::walk (MeshPoint p, size_t t_now)
Walks to the next closest triangle.
Parameters
p MeshPoint to locate
t_now Index of current triangle
Returns
index of adjacent triangle to walk to
Definition at line 250 of file Mesh.cpp.
References centroid(), edgesOfTriag(), edgeToLineSeg(), LineSeg::isCross(), and triagOfEdge().
Referenced by search().
The documentation for this class was generated from the following files:
src/Mesh.hpp
src/Mesh.cpp